from adafruit_hid.keycode import Keycode

MEDIA = 1
KEY = 2
LAYER = 3
NONE = 3

EMPTY_ROW = {
    0: (NONE, 0, "None"),
    1: (NONE, 0, "None"),
    2: (NONE, 0, "None"),
    3: (NONE, 0, "None"),
    4: (NONE, 0, "None"),
    5: (NONE, 0, "None"),
    6: (NONE, 0, "None"),
    7: (NONE, 0, "None"),
    8: (NONE, 0, "None"),
    9: (NONE, 0, "None"),
    10: (NONE, 0, "None"),
    11: (NONE, 0, "None"),
}

# format is [layer_number][row]{[(type, code, name)]}
keymap = [
    # layer 0
    {
        0: {
            0: (KEY, Keycode.ESCAPE, "Esc"),
            1: (KEY, Keycode.Q, "Q"),
            2: (KEY, Keycode.W, "W"),
            3: (KEY, Keycode.E, "E"),
            4: (KEY, Keycode.R, "R"),
            5: (KEY, Keycode.T, "T"),
            6: (KEY, Keycode.Y, "Y"),
            7: (KEY, Keycode.U, "U"),
            8: (KEY, Keycode.I, "I"),
            9: (KEY, Keycode.O, "O"),
            10: (KEY, Keycode.P, "P"),
            11: (KEY, Keycode.BACKSPACE, "Backspace"),
        },
        1: {
            0: (KEY, Keycode.TAB, "Tab"),
            1: (KEY, Keycode.A, "A"),
            2: (KEY, Keycode.S, "S"),
            3: (KEY, Keycode.D, "D"),
            4: (KEY, Keycode.F, "F"),
            5: (KEY, Keycode.G, "G"),
            6: (KEY, Keycode.H, "H"),
            7: (KEY, Keycode.J, "J"),
            8: (KEY, Keycode.K, "K"),
            9: (KEY, Keycode.L, "L"),
            10: (KEY, Keycode.SEMICOLON, "Semicolon"),
            11: (KEY, Keycode.QUOTE, "Quote"),
        },
        2: {
            0: (KEY, Keycode.LEFT_SHIFT, "Shift"),
            1: (KEY, Keycode.Z, "Z"),
            2: (KEY, Keycode.X, "X"),
            3: (KEY, Keycode.C, "C"),
            4: (KEY, Keycode.V, "V"),
            5: (KEY, Keycode.B, "B"),
            6: (KEY, Keycode.N, "N"),
            7: (KEY, Keycode.M, "M"),
            8: (KEY, Keycode.COMMA, "Comma"),
            9: (KEY, Keycode.PERIOD, "Period"),
            10: (KEY, Keycode.FORWARD_SLASH, "Forward Slash"),
            11: (KEY, Keycode.ENTER, "Enter"),
        },
        3: {
            0: (LAYER, 3, "Layer 3"),
            1: (KEY, Keycode.LEFT_CONTROL, "Ctrl"),
            2: (KEY, Keycode.LEFT_ALT, "Alt"),
            3: (KEY, Keycode.COMMAND, "Cmd"),
            4: (LAYER, 1, "Layer 1"),
            5: (KEY, Keycode.SPACEBAR, "Space"),
            6: (KEY, Keycode.SPACEBAR, "Space"),
            7: (LAYER, 2, "Layer 2"),
            8: (KEY, Keycode.LEFT_ARROW, "Left Arrow"),
            9: (KEY, Keycode.DOWN_ARROW, "Down Arrow"),
            10: (KEY, Keycode.UP_ARROW, "Up Arrow"),
            11: (KEY, Keycode.RIGHT_ARROW, "Right Arrow"),
        },
    },
    # layer 1
    {
        0: {
            0: (KEY, Keycode.GRAVE_ACCENT, "`"),
            1: (KEY, Keycode.ONE, "1"),
            2: (KEY, Keycode.TWO, "2"),
            3: (KEY, Keycode.THREE, "3"),
            4: (KEY, Keycode.FOUR, "4"),
            5: (KEY, Keycode.FIVE, "5"),
            6: (KEY, Keycode.SIX, "6"),
            7: (KEY, Keycode.SEVEN, "7"),
            8: (KEY, Keycode.EIGHT, "8"),
            9: (KEY, Keycode.NINE, "9"),
            10: (KEY, Keycode.ZERO, "0"),
            11: (KEY, Keycode.DELETE, "Delete"),
        },
        1: {
            0: (NONE, 0, "None"),
            1: (NONE, 0, "None"),
            2: (NONE, 0, "None"),
            3: (NONE, 0, "None"),
            4: (NONE, 0, "None"),
            5: (NONE, 0, "None"),
            6: (NONE, 0, "None"),
            7: (KEY, Keycode.MINUS, "-"),
            8: (KEY, Keycode.EQUALS, "="),
            9: (KEY, Keycode.LEFT_BRACKET, "["),
            10: (KEY, Keycode.RIGHT_BRACKET, "]"),
            11: (KEY, Keycode.BACKSLASH, "\\"),
        },
        2: {
            0: (KEY, Keycode.LEFT_SHIFT, "Shift"),
            1: (NONE, 0, "None"),
            2: (NONE, 0, "None"),
            3: (NONE, 0, "None"),
            4: (NONE, 0, "None"),
            5: (NONE, 0, "None"),
            6: (NONE, 0, "None"),
            7: (NONE, 0, "None"),
            8: (NONE, 0, "None"),
            9: (NONE, 0, "None"),
            10: (NONE, 0, "None"),
            11: (NONE, 0, "None"),
        },
        3: {
            0: (LAYER, 3, "Layer 3"),
            1: (NONE, 0, "None"),
            2: (NONE, 0, "None"),
            3: (NONE, 0, "None"),
            4: (LAYER, 1, "Layer 1"),
            5: (NONE, 0, "None"),
            6: (NONE, 0, "None"),
            7: (LAYER, 2, "Layer 2"),
            8: (NONE, 0, "None"),
            9: (NONE, 0, "None"),
            10: (NONE, 0, "None"),
            11: (NONE, 0, "None"),
        }
    },
    # layer 2
    {
        0: {
            0: (KEY, Keycode.F1, "F1"),
            1: (KEY, Keycode.F2, "F2"),
            2: (KEY, Keycode.F3, "F3"),
            3: (KEY, Keycode.F4, "F4"),
            4: (KEY, Keycode.F5, "F5"),
            5: (KEY, Keycode.F6, "F6"),
            6: (KEY, Keycode.F7, "F7"),
            7: (KEY, Keycode.F8, "F8"),
            8: (KEY, Keycode.F9, "F9"),
            9: (KEY, Keycode.F10, "F10"),
            10: (KEY, Keycode.F11, "F11"),
            11: (KEY, Keycode.F12, "F12"),
        },
        1: EMPTY_ROW,
        2: EMPTY_ROW,
        3: {
            0: (LAYER, 3, "Layer 3"),
            1: (NONE, 0, "None"),
            2: (NONE, 0, "None"),
            3: (NONE, 0, "None"),
            4: (LAYER, 1, "Layer 1"),
            5: (NONE, 0, "None"),
            6: (NONE, 0, "None"),
            7: (LAYER, 2, "Layer 2"),
            8: (NONE, 0, "None"),
            9: (NONE, 0, "None"),
            10: (NONE, 0, "None"),
            11: (NONE, 0, "None"),
        }
    },
    # layer 3
    {
        0: EMPTY_ROW,
        1: EMPTY_ROW,
        2: EMPTY_ROW,
        3: {
            0: (LAYER, 3, "Layer 3"),
            1: (NONE, 0, "None"),
            2: (NONE, 0, "None"),
            3: (NONE, 0, "None"),
            4: (LAYER, 1, "Layer 1"),
            5: (NONE, 0, "None"),
            6: (NONE, 0, "None"),
            7: (LAYER, 2, "Layer 2"),
            8: (NONE, 0, "None"),
            9: (NONE, 0, "None"),
            10: (NONE, 0, "None"),
            11: (NONE, 0, "None"),
        }
    },
]
